export const LOGIN_SUCCESS = "Login Successfully";
export const INVALID_CREDENTIALS = "Invalid credentials";
export const INVALID_EMAIL = "Invalid email";
export const INVALID_PASSWORD = "Invalid password";
export const SIGNUP_SUCCESS = "Signup Successfully";
export const CONFIRM_PASSWORD_ERROR = "Not match with password";
export const EMAIL_EXIST = "Email already registered";
export const INVALID_USER_EMAIL = "Invalid user email ";

export const PASSWORD_MINLENGTH = "minimum length of password is 4";
export const PASSWORD_MAXLENGTH = "maximum length of password is 20";
export const Email_REQUIRED = "Email is required";
export const PASSWORD_REQUIRED = "Password is required";
export const FNAME_REQUIRED = "First name is required";
export const LNAME_REQUIRED = "Last name is required";
export const NAME_VALIDATION = "Username cannot consist only of blank spaces";
export const PHONE_VALIDATION = "Must be a number";
export const PHONE_REQUIRED = "Phone number is required";
export const UPDATED_PASSWORD = "User password update successfully";